workflows:
  ios-app:
    name: Build iOS App
    environment:
      xcode: 15.0
    scripts:
      - name: Build iOS project
        script: |
          xcodebuild build -project "Leprechaun.xcodeproj" -scheme "Leprechaun" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - build/ios/xcarchive/*.xcarchive.zip
